### ISSUE TITLE
Graphic artifact when swiping fast

### ISSUE THREAD

**Issue by jerometonnelier** [John-Lluch/SWRevealTableViewCell#7]
![capture decran du simulateur ios 23 juil 2014 11 59 55](https://cloud.githubusercontent.com/assets/1484522/3671462/2184df28-1250-11e4-9919-80f224d18679.png)
When the user swipes fast to reveal the underlying buttons (and theses buttons have a backgroundColor), there is a small white gap between buttons when they are stretched the first time. 
After, the artifact is no longer present

**Comment by John-Lluch** [comment]
Hi, I think saw this on an earlier version, are you using the very last version?. Please can you disclose the reveal mode you are using, such as reversed or not, and whether this does make a difference? Are you on iOS7 or iOS8? Thanks

**Comment by jerometonnelier** [comment]
Hi ;)
I use a only left items, there are no options set (I didn't know there was a reverse mode :D). It's on iOS7 on the simulator. It only happens when I literally throw the cell very fast. If I reveal the buttons slowly and stretch it at maximum resistance, there is no such effect. I use the cocoa pods version, I assume it is the latest right?

Since I'm here, I had a couple of questions : it seems that by default, the button are added to a view that has the sameBackgroudColor as the contentView of the cell. Isn't there a way to use a clear color so that the button can be translucent? Thanks ;-)

**Comment by John-Lluch** [comment]
Hi, Latest version is v0.3.0. I will try to reproduce this.

Buttons are added to a custom view that is added to the cell, not to the contentView, so the ultimate background is the cell's background. Setting a background to your content view should not have an effect to the buttons. 

Indeed buttons can be translucent and show the tableView underneath if you also set your cell's background to transparent (not its contentView's). Hope this helps.

**Comment by jerometonnelier** [comment]
Thanks for all of this, I'll have a look at it right now ;)

**Comment by maddoggy1979** [comment]
Based on John's note above, I set my cell's contentview background color as white, and the cell's background color to blue (i also have only blue buttons on the left).
This reduced the white artefact when you swipe quickly, but its still barely there.
This won't really work if buttons are all different colors.

I presume this is because the buttons only cover the width you configure them at, yet pulling the cell further then creates a gap.
Perhaps a solution is for the buttons to slightly overlap (or underlap :s) the next cell, which would alleviate any "white-space" between them when the cell is pulled too far?

Thoughts?

**Comment by jerometonnelier** [comment]
I'm not sure that overlapping is a solution since if the background is semi transparent, overlapping of 2 semi transparent areas will result in a less transparent area :-/

**Comment by John-Lluch** [comment]
Hi, I definitely can NOT reproduce this. Please can you post the exact cell configuration and steps to reproduce it so I can have a chance to look at it. Thanks

By the way, the class simulates item overlap but button items do not actually overlap, they just _appear_ to do so, this is by design to allow translucency. Jerometonnelier is right that buttons should not overlap or translucency will not work.

**Comment by John-Lluch** [comment]
Hi again, 
Ok, so I used same color for items (should have done that from the beginning) and was able to see it. After some debugging and testing I found that artifacts happen only during animated dampening (possibly due to value rounding in the GPU). So in fact this is not technically a fault of the class, except for the fact that we want to avoid view overlapping.

I tested several workarounds and found that only by adding half a point (on retina) to the width of items at the time of layout, artifacts disappear completely. 
Please try to add 
`lWidth += 1/scale;`
just _after_
`CGFloat scale = Scale();` 
in 
`- (void)_layoutViewsForNewPosition:(SWCellRevealPosition)newPosition location:(CGFloat)xLocation`
and all artifacts are gone.

HOWEVER, this adds a slightly noticeable overlap when items are translucent.

**Comment by John-Lluch** [comment]
Hi again. The issue should be fixed now (v0.3.3). Thanks

**Comment by maddoggy1979** [comment]
Hi John,
Thanks for your work on this. I still have the background showing between buttons when opened. It's better than it previously was, and not that much of a distraction when run on my iphone5. Basically, its exactly the same as the original screenshot in Jerome's post. 
However, when run on the iphone4S simulator, a white background glares through, and in one instance it shows through a fair bit, as below. I can't produce those exaggerated gaps on a phone device, but it may show up on an ipad where you can drag further, I just don't have an ipad to test with.
![screen shot 2014-07-25 at 7 41 56 am](https://cloud.githubusercontent.com/assets/8011491/3695258/f4b42a8a-137b-11e4-8527-7a8298eed6ac.png)

My cellForRowAtIndexPath is below. Nothing non-standard there. The PersonCell is just a normal custom cell with a couple of labels and an imageview.

``` objective-c
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    PersonCell *cell = [self.tableView dequeueReusableCellWithIdentifier:@"personCell" forIndexPath:indexPath];
    cell.delegate = self;
    cell.dataSource = self;
    //cell.backgroundColor = _blueColor;
    Person *person = [_dataArray objectAtIndex:indexPath.row];

    cell.mainText.text = [NSString stringWithFormat:@"%@ %@", person.firstname, person.lastname];
    Company *company = (Company *)person.worksFor;
    cell.companyTitle.text = company.name;

    if ([person hasPhoto]) {
        _image = [person photoImage];
        if (_image != nil) {
            cell.personImageView.image = _image;
            cell.personImageView.layer.cornerRadius = cell.personImageView.bounds.size.width / 2.0f;
            cell.personImageView.clipsToBounds = YES;
        }
    }
    return cell;
}
```

**Comment by jerometonnelier** [comment]
Sorry for this late reply John, I was quite busy yesterday. I'll have a look at it right now before updating my cocapods!

**Comment by John-Lluch** [comment]
Hi maddoggy1979, It is important to understand why _I think_ this happens. It is not due to an error or bug on the class layout code, but to lost frames during animation rendering on which we do not have any control. The fact that we want items to not overlap means that they are laid out one next to the other with no gaps in between. If frames are lost during animation rendering then items may appear to either overlap or to create a gap during very short times (1/60 of a second). I suppose that the more load is on the GPU the more this is prone to happen. 

Due to the nature of the issue this can not be solved unless we accept some compromises: We can:
1 - Abandon the non-overlaping approach on items. This would make the class to fail for translucent background items, and I am not 100% sure that this would _completely_ and _definitely_ solve the glitch either.

2 - Abandon animations on items. This would keep items static on place as you pull the cell further than full open. This would presumably completely remove the glitch, but would make the control less attractive.

3 - Life with it as it is given that this glitch is really hard to reproduce and needs very strong user action to be created. My take on that is that only trained graphic designers will be able to actually see it, but your perception may vary.

Please let me know the one from above that you would take. Of course, I can be missing something, so any suggestions are appreciated. Just to let you know, I would take number 3 because since the last update (v0.3.3) I have never seen the glitch again, see below.

The most I could see by running the example was a thin line gap between items in very rare occasions after a strong swipe user gesture. This gap was never wider than 1/2 point (1 pixel in retina display). I solved that by checking color opacity on items and adding 1/2 point to item widths if they are opaque. This completely removed the glitch for me. By the way, are your item backgrounds fully opaque?

I never have seen such a huge gap as in your screenshot. How did you take it? are you capturing a video of the full animation and then extract a single frame?. I am curious on that. Also, if you still think that this is significant I'd appreciate that you take some time to create a simple project, or modifying the example to make this reproducible in the easiest possible way. I ask you so because I just run the example on iPhone4s, iOS8 simulator, tried very hard to produce the glitch but it didn't happen to me.

Thanks.

**Comment by jerometonnelier** [comment]
It seems to work indeed (at least like you say, there are still some minor artifacts, but it's much much better now). Thanks again for your help and for this amazing library ;-)

**Comment by jerometonnelier** [comment]
Given your 3 options before, maybe (but I think it would be a lot a work), you can add an option that allows us to choose between animated and non animated items when revealing the items? I personally thinks it would a great great improvement ;-)

**Comment by maddoggy1979** [comment]
Hi John,
For my purposes, the small gap is negligible when using it on a device (iphone5 in my case). All my buttons are the same color, so I can further minimise anything a user may see by setting an appropriate background color, as mentioned previously.

My screenshot above was done by using the iOS Simulator, and using Quicktime Player to record the screen - then I just took a screen shot of that particular frame in the video while it was paused. I haven't actually seen that size gap when using my phone.

As an interesting side note - the gap is easier to reproduce on the left buttons.. not so much on the right.

Anyway... long story short - 0.3.3 is a good improvement and I'm happy with that (and grateful for your quick and helpful response).

I also just replicated it in a fresh project - both with storyboards and without. No additional cell setup other than this (and the buttons of course):

``` objective-c
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    SWRevealTableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:RevealCellReuseIdentifier];
    if ( cell == nil )
    {
        cell = [[SWRevealTableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:RevealCellReuseIdentifier];
    }
    cell.delegate = self;
    cell.dataSource = self;
    cell.textLabel.text = @"cell text";
    return cell;
}
```

Thanks

**Comment by xisintag** [comment]
Hi John

I can't get the transparency to work for Buttons with Images, as shown in the attached Example using the following code:

item1.backgroundColor = [UIColor colorWithRed:0.5f green:0.5f blue:0.5f alpha:0.5f];
item1.tintColor = [UIColor whiteColor];
item1.width = 50;

Your suggestions are much appreciated

**Comment by John-Lluch** [comment]
xisintag, please post this on a separate issue. Thanks

**Comment by John-Lluch** [comment]
Hi @maddoggy1979, thanks for your feedback. I would appreciate that you comment as well on your take on my 3 possible workarounds I posted above. 

I think that @jerometonnelier has a point on this. He suggested to implement an option to have 'non animated items' (I understand he means like iOS7 mail), this is even more conservative than my approach 2. Additionally, it should be possible to go further by implementing as well a 'full overlap' mode as per my approach 1. Ultimately giving more options will satisfy more users :-). I will have a look at it when I have some time, I think it should not be a lot of additional code. Thanks

**Comment by maddoggy1979** [comment]
@John-Lluch - I only just came back and saw your latest post...
My comments about the 3 suggestions are below.

> 1 - Abandon the non-overlaping approach on items. This would make the class to fail for translucent background items, and I am not 100% sure that this would completely and definitely solve the glitch either.

I agree. Not really an option.

> 2 - Abandon animations on items. This would keep items static on place as you pull the cell further than full open. This would presumably completely remove the glitch, but would make the control less attractive.

I agree. Perhaps this can be a toggled option in the API. As you say, it would be less attractive - the spring/bounce of the sliding buttons makes it feel a lot nicer.

> 3 - Life with it as it is given that this glitch is really hard to reproduce and needs very strong user action to be created. My take on that is that only trained graphic designers will be able to actually see it, but your perception may vary.

Due to the very minimal and very occasional impact that this has on my app, I am more than happy to leave it as-is. My buttons on the left are all the same color so perhaps this helps to minimise any artefacts that usually appear as white.

I agree with your suggestion about jerome's option....
